---
title: "Instacart Dataset"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(viridis)
library(p8105.datasets)
library(plotly)
library(ggridges)
data(instacart)
```

Column {data-width=550}
-----------------------------------------------------------------------

### Chart A

```{r top_items}

top_items = 
  instacart %>% 
  count(product_name) %>% 
  top_n(20)

top_items %>% 
  mutate(product_name = as.factor(product_name),
         product_name = fct_reorder(product_name, n)) %>% 
  plot_ly(x = ~product_name, y = ~n, color = ~product_name, type = "bar", hoverinfo = 'text',
          text = ~paste('</br> Product Name: ', product_name,
                        '</br> Number of Items: ', n)
          ) %>% 
  layout(title = "Top 10 Items Ordered", 
         xaxis = list(title = "Product Name"), 
         yaxis = list(title = "Number of Items"))
top_items
```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart B

```{r instacart_items}
set.seed(1)

instacart_sample = 
  instacart %>% 
  sample_n(10000)

instacart_sample %>%
  group_by(order_hour_of_day, department) %>% 
  summarize(count = n()) %>%
  plot_ly(x = ~order_hour_of_day, y = ~count, color = ~department, 
          type = "scatter", mode = "markers", hoverinfo = 'text',
          text = ~paste('</br> Department: ', department,
                        '</br> Number of Items: ', count,
                        '</br> Hour: ', order_hour_of_day)
          ) %>% 
  layout(
    title = "Number of Items Ordered by Department", 
    xaxis = list(title = "Time of Day"),
    yaxis = list(title = "Number of Items")
    )

instacart_sample
```

### Chart C

```{r dist_of_orders}
set.seed(1)

dist_of_orders =
  instacart %>%
  sample_n(10000) %>% 
  mutate(order_dow = recode(order_dow, 
                            `0` = "Sunday", 
                            `1` = "Monday", 
                            `2` = "Tuesday", 
                            `3` = "Wednesday", 
                            `4` = "Thursday", 
                            `5` = "Friday", 
                            `6` = "Saturday"), 
         order_dow = forcats::fct_relevel(order_dow, c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"))
         ) %>% 
  plot_ly(x = ~order_dow, y = ~order_hour_of_day, color = ~order_dow, type = "box") %>% 
   layout(
     title = "Distribution of Orders by Day of the Week", yaxis = list(title = "Hour"), xaxis = list(title = "Day of the Week"))

dist_of_orders
```
